### ISSUE TITLE
zero-shot for EE datasets？

### ISSUE THREAD

**Issue by JunxiuChen** [BeyonderXX/InstructUIE#26]
Hello, thanks you for your contribution! I'd like to ask you two questions: 
1. May I ask why there is no zero-shot experiment on event extraction datasets?
2. Can the model be modified to the few-shot setting? If so, what should I pay attention to?

Looking forward to your reply!

**Comment by BeyonderXX** [comment]
1. Two reasons. One is because the data set of EE is relatively small and the general EE ability of model learning is relatively poor. The other is that EE is indeed much more difficult than NER and RE, so there is no zero-shot of EE.
2. It can be adapted to few-shot, but few-shot training is required, otherwise there will be a gap between training and testing. Now that we have trained, there should be little difference between zero-shot and few-shot.

Xiao Wang
